name: Testing - Reusable Workflow
on: 
  workflow_call:
    inputs:
      ingress_url:
        required: true
        description: "description"
        type: string
      
jobs:
  integration-test:
    runs-on: ubuntu-latest
    steps:
      - env:
          URL: '${{ inputs.ingress_url }}'
        run: |
          curl https://$URL/live -s -k | jq -r .status | grep -i live
